---
- hosts: localhost

  vars_prompt:
    - name: 'password'
      prompt: 'Please enter the admin user password'
      private: yes

  tasks:
  - name: get all realms
    realms:
      username: admin
      password: '{{ password }}'
    no_log: True
    register: realms_results

  - name: dump realms results
    debug:
      msg: '{{ realms_results }}'

  - name: get a single realm
    realms:
      username: admin
      password: '{{ password }}'
    no_log: True
    register: single_realm_results

  - name: dump single realm results
    debug:
      msg: '{{ single_realm_results }}'
